# Generated by Django 5.0.8 on 2024-08-11 20:33

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
